### ISSUE TITLE
Completely impossible to add as a dependency if also using Spray

### ISSUE THREAD

**Issue by samthebest** [sirthias/parboiled2#127]
I have tried just about everything, I've played around with easily 100 different build files now, and 18 hours of development time just trying to add parboiled2 as a dependency to our project and run `sbt assembly`.  I'm coming to the conclusion that it would be cheaper to stick with Scala's native (but slower) parsers and upgrade our AWS servers to more powerful instances (just kidding, but really I'm finding this a total nightmare).

Anyway the problems we have been having seem to be that both Spray and Parboiled2 have a transative dependency on Shapeless.  I've documented in detail what I've been trying on these SOs:

Scala 2.10:
http://stackoverflow.com/questions/27658468/parboiled2-and-spray-cause-conflicting-cross-version-suffixes

Scala 2.11:
http://stackoverflow.com/questions/27942110/parboiled2-causes-missing-or-invalid-dependency-detected-while-loading-class-fi

Please have a read, and please please help me write a build file that actually works with both Parboiled2 and Spray.

**Comment by sirthias** [comment]
pb2 depends on shapeless 2.0.
The default spray releases depend on shapeless 1.x.
So you cannot have both libraries on the classpath at the same time.
However, we have published a special release of spray-routing, which depends on shapeless 2.0.
It's called `spray-routing-shapeless2`. You can get it from http://repo.spray.io.
(See here: http://repo.spray.io/io/spray/)

With this build (instead of the default `spray-routing` module) running spray and pb2 at the same time should be no problem.

**Comment by jrudolph** [comment]
I added an example to the spray-template project which shows spray-routing-shapeless2 / parboiled integration:

https://github.com/spray/spray-template/blob/on_spray-can_1.3_shapeless2_scala-2.11/build.sbt

**Comment by samthebest** [comment]
Yes, finally! It works, thanks!  I've updated your documentation, it may save the time of future SBT noobs.

So excited to use this!
