### ISSUE TITLE
Outdated snapshot builds

### ISSUE THREAD

**Issue by pniederw** [sirthias/parboiled2#151]
Looking at https://oss.sonatype.org/content/repositories/snapshots/org/parboiled/parboiled_2.11/, the latest snapshot is from Nov 30, 2014. Can we have an update please (ideally regularly)?

**Comment by sirthias** [comment]
I only publish snapshots if and when there is something to publish.
Currently there simply isn't.
What problem are you trying to solve?

**Comment by pniederw** [comment]
I switched to the rules-as-objects architecture, but building/publishing my own snapshots isn’t fun.

It would be better if new snapshots were published automatically (e.g. nightly builds that pass all tests). “if there is something to publish” is when a new release should be published.

**Comment by sirthias** [comment]
Peter, if you already switched to the current master then you are definitely ahead of the curve. :)
While this latest implementation is much better than the 2.1 release it is, unfortunately, not quite ready for prime-time yet. Apart from the missing documentation the macro infrastructure is not as robust yet as I'd like to be for version 2.2.
But, since you are as bold as you are, I'm going to publish a snapshot just for you. :)
I'll report back when it's done.

**Comment by sirthias** [comment]
Ok, 2.2.0-SNAPSHOT is now available from sonatype.
