### ISSUE TITLE
Facilitate position tracking for created values

### ISSUE THREAD

**Issue by bobziuchkovski** [sirthias/parboiled2#79]
I'm creating this issue in relation to the discussion at https://groups.google.com/forum/#!msg/parboiled-user/Aoxz1E9bwPM/AUplpjala6wJ

This is a feature request to add support for a general mechanism to associate cursor position with values that are pushed to the stack.   I honestly don't know what it would look like, but a half-formed idea would be to support scala.util.parsing.input.Positional.  In a push action, test if the value object implements Positional, and if so, call setPos on it.  scala.util.parsing.input.OffsetPosition could be used for the Position -- it handles line counting automatically.

Justification: With a complex AST, manually polling cursor position leads to repetitive and error-prone code.  In my use case, I'm writing a prototype DCE RPC compiler, and there are approximately 100 different AST case classes that can be pushed to the stack (DCE IDL specifies a number of different type and value attributes).  Associating parser position with the AST nodes is necessary in order to report meaningful error messages during semantic analysis.  Anything to make that position handling DRY would be very helpful.

**Comment by Vadi** [comment]
+1 for somehow tracking positions. While i understand the rationale behind why a tracking input positions aren't the responsibility of Parboiled, I see a need for knowing which line/col is parsed so far. There is no way yet I guess.

Justification: I am writing editor for JSON. Need to know which object is parsed so far etc.,

**Comment by WojciechKarpiel** [comment]
> Tracking input positions and attaching them to your custom AST types is something that really does fall within the responsibility of the application, not parboiled.

I think a nice compromise would be to add an [example](https://github.com/sirthias/parboiled2/tree/master/examples/src/main/scala/org/parboiled2/examples) of how to do this application-side

Why it would be cool?

Chances are that you want to track positions from the very start, from your serious attempt at writing a parser with Parboiled. Since you're just starting, you're likely unaware that `push(cursor)` is basically a good-enough solution to get you going. You look for examples, and if there was an example of [this pattern](https://github.com/sirthias/parboiled2/issues/98#issuecomment-62135712), then it would solve your issue


----

fun fact: I myself was in such situation, and OpenAI's O1-preview showed me the `push(cursor)` pattern when asked about position-tracking in Parboiled
